var PROVINCES = {
  '北京': ["beijing"],
  '天津': ["tianjin"],
  '上海': ["shanghai"],
  '重庆': ["chongqing"],
  '河北': ["shijiazhuang", "tangshan", "baoding", "handan", "langfang", "cangzhou", "qinhuangdao", "xingtai", "zhangjiakou", "chengde", "hengshui"],
  '山西': ["taiyuan", "datong", "yangquan", "changzhi", "jincheng", "jinzhong", "yuncheng", "xinzhou", "linfen", "lvliang"],
  '内蒙古': ["hohhot", "baotou", "chifeng", "tongliao", "ordos", "hulunbuir", "bayannur", "wulanchabu"],
  '辽宁': ["shenyang", "dalian", "anshan", "fushun", "benxi", "dandong", "jinzhou", "yingkou", "fuxin", "liaoyang", "panjin", "tieling", "chaoyang", "huludao"],
  '吉林': ["changchun", "jilin", "siping", "liaoyuan", "tonghua", "baishan", "songyuan", "baicheng"],
  '黑龙江': ["harbin", "qiqihar", "jixi", "hegang", "shuangyashan", "daqing", "yichun", "jiamusi", "qitaihe", "mudanjiang", "heihe", "suihua"],
  '江苏': ["nanjing", "suzhou", "wuxi", "changzhou", "nantong", "yangzhou", "zhenjiang", "yancheng", "xuzhou", "huaian", "lianyungang", "taizhou_js", "suqian"],
  '浙江': ["hangzhou", "ningbo", "wenzhou", "jiaxing", "huzhou", "shaoxing", "jinhua", "quzhou", "zhoushan", "taizhou_zj", "lishui"],
  '安徽': ["hefei", "wuhu", "bengbu", "huainan", "maanshan", "huaibei", "tongling", "anqing", "huangshan", "chuzhou", "fuyang", "suzhou_ah", "luan", "bozhou", "chizhou", "xuancheng"],
  '福建': ["fuzhou", "xiamen", "quanzhou", "zhangzhou", "nanping", "longyan", "ningde", "putian", "sanming"],
  '江西': ["nanchang", "jiujiang", "jingdezhen", "pingxiang", "xinyu", "yingtan", "ganzhou", "jian", "yichun_jx", "fuzhou_jx", "shangrao"],
  '山东': ["jinan", "qingdao", "yantai", "weifang", "weihai", "zibo", "linyi", "jining", "taian", "dongying", "binzhou", "dezhou", "liaocheng", "heze", "rizhao", "zaozhuang"],
  '河南': ["zhengzhou", "luoyang", "kaifeng", "pingdingshan", "anyang", "hebi", "xinxiang", "jiaozuo", "puyang", "xuchang", "luohe", "sanmenxia", "nanyang", "shangqiu", "xinyang", "zhoukou", "zhumadian"],
  '湖北': ["wuhan", "huangshi", "shiyan", "yichang_hb", "xiangyang", "ezhou", "jingmen", "xiaogan", "jingzhou", "huanggang", "xianning", "suizhou", "enshi"],
  '湖南': ["changsha", "zhuzhou", "xiangtan", "hengyang", "shaoyang", "yueyang", "changde", "zhangjiajie", "yiyang", "chenzhou", "yongzhou", "huaihua", "loudi"],
  '广东': ["guangzhou", "shenzhen", "zhuhai", "shantou", "foshan", "shaoguan", "zhanjiang", "zhaoqing", "jiangmen", "maoming", "huizhou", "meizhou", "shanwei", "heyuan", "yangjiang", "qingyuan", "dongguan", "zhongshan", "chaozhou", "jieyang", "yunfu"],
  '广西': ["nanning", "liuzhou", "guilin", "wuzhou", "beihai", "fangchenggang", "qinzhou", "guigang", "yulin_gx", "baise", "hezhou", "hechi", "laibin", "chongzuo"],
  '海南': ["haikou", "sanya", "danzhou"],
  '四川': ["chengdu", "mianyang", "deyang", "zigong", "panzhihua", "luzhou", "guangyuan", "suining", "neijiang", "leshan", "nanchong", "meishan", "yibin", "guangan", "dazhou", "yaan", "bazhong", "ziyang"],
  '贵州': ["guiyang", "zunyi", "liupanshui", "anshun", "bijie", "tongren"],
  '云南': ["kunming", "qujing", "yuxi", "baoshan", "zhaotong", "lijiang", "puer", "lincang"],
  '西藏': ["lhasa", "shigatse", "qamdo", "nyingchi", "shannan", "nagqu"],
  '陕西': ["xian", "xianyang", "baoji", "weinan", "yanan", "hanzhong", "yulin_sx", "ankang", "shangluo"],
  '甘肃': ["lanzhou", "jiayuguan", "jinchang", "baiyin", "tianshui", "wuwei", "zhangye", "pingliang", "jiuquan", "qingyang", "dingxi", "longnan"],
  '青海': ["xining", "haidong"],
  '宁夏': ["yinchuan", "shizuishan", "wuzhong", "guyuan", "zhongwei"],
  '新疆': ["urumqi", "karamay", "turpan", "hami", "changji", "bortala", "bayingolin", "aksu", "kizilsu", "kashgar", "hotan", "ili", "tacheng", "altay"],
};
